# Generated by Django 2.2.7 on 2020-01-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlienta', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('numerTelefonu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('idProduktu', models.IntegerField(primary_key=True, serialize=False)),
                ('rodzaj', models.CharField(max_length=30)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('idZamowienia', models.IntegerField(primary_key=True, serialize=False)),
                ('ilosc', models.IntegerField()),
                ('idKlienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.Klient')),
                ('idProduktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.Produkt')),
            ],
        ),
    ]
